### ISSUE TITLE
cannot set default terms using wp_insert_term since it requires the init hook

### ISSUE THREAD

**Issue by mmccook** [mboynes/super-cpt#14]
as the title says wp_insert_term cannot be used to setup defaults since it requires being called on init and not after_setup_theme. 

Any ideas how to get this to work?

**Comment by mboynes** [comment]
While you run your SuperCPT code on after_setup_theme, the taxonomies and
post types are registered on init. You can still set default terms on init,
no problem, just do it in another function or method. Use a priority >10 on
your init hook to be certain the taxonomy is registered.

**Comment by mmccook** [comment]
Ahh thanks
