### ISSUE TITLE
How do you set default radio/checkbox value in Super_Custom_Post_Meta?

### ISSUE THREAD

**Issue by Gyroscopic** [mboynes/super-cpt#15]
Hi

I've tried the wiki and all web tuts for Super-CPT but cannot find out how to set a default radio item.

I tried using 'default' => 'blue' in the 'fields' declaration section but it didnt work. Is this currently available and if not can you implement it please.

**Comment by mboynes** [comment]
Good suggestion, thanks. This should be very easy to do, so I'll have it in the next release!

**Comment by Gyroscopic** [comment]
Excellent - thanks. Any idea when the next release will be?

**Comment by mboynes** [comment]
It will be right after the WordPress 3.6 release, so hopefully soon!
