### ISSUE TITLE
Add taxonomy column to post list table?

### ISSUE THREAD

**Issue by Gyroscopic** [mboynes/super-cpt#19]
Hi I couldn't find a way to get super-cpt to add the taxonomy column to the post list page. Is this already available or if not can you add it on the next version possibly?

I am using the usual wp code...

```
$category = new Super_Custom_Taxonomy( ... );

function my_projectcat_edit_columns( $columns ) {
    $columns['custom_cat'] = __('Custom Cat');
    return $columns;
}
function my_projectcat_custom_content( $column ) {
    global $post;
    if ($column == 'custom_cat') { 
        echo get_the_term_list( $post->ID, 'custom_cat', '', ', ', '' );
    } else {
        null;
    }
}
add_filter('manage_project_posts_columns', 'my_projectcat_edit_columns');  
add_action('manage_project_posts_custom_column', 'my_projectcat_custom_content');  
```

...to get around it at the moment but it means extra lines of code for each cpt definition

**Comment by Gyroscopic** [comment]
Thats great - thanks! 

How do we utilise it though, as the docs have not been updated yet (I know its only been 8hrs :)

**Comment by mboynes** [comment]
Hah, thanks for understanding.

`$cpt->add_to_columns( 'tax-slug' );`
