### ISSUE TITLE
change date format and use the date to classify posts

### ISSUE THREAD

**Issue by danycerone** [mboynes/super-cpt#20]
Hi,

I was wondering how to get the date from a date meta box into another format in a wp query.
Also I am making a website with events and I can't find a way to get the custom posts order according to which will happen the soonest. This would inply to first check the date of the day and remove events which end the has already happens and then classify the other in the wp query arg according to which one is the soonest.

I hope someone can help me and that I a clear enough for what I ask

**Comment by treiber** [comment]
I would also like that functionality,
currently my only solution is to add the meta box with standard wp syntax and convert the date format then.

**Comment by mboynes** [comment]
You can store the date in any format you choose using the filter, scpt_plugin_{$post_type}_meta_save_{$field}. For example, for a post type of "event" and a meta field of "start_date", you would use the filter "scpt_plugin_event_meta_save_start_date". The date will come in the format yyyy-mm-dd, and you can use `strtotime()` or similar to parse that into any format you'd like. You can then use the meta fields in WP_Query to restrict the data how you need, which would be very easy to do (date > now, order by date asc)
