### ISSUE TITLE
Undefined Index, please help?

### ISSUE THREAD

**Issue by ghost** [mboynes/super-cpt#21]
Hi there, 

I am trying to get meta boxes to work on a Custom Post Type "team". I have added the following:

```
$teams = new Super_Custom_Post_Type( 'team', 'Team Member', 'Team Members' );
$teams->add_meta_box( array(
    'id' => 'title',
    'context' => 'normal',
    'fields' => array(
        'Team Member Title' => array(),
    )
) );
```

When editing the page in the WordPress backend I get an "Undefined index" above the field. If I flush my permalinks it goes away but when trying to save the post I get the following:

Notice: Undefined index: Team Member Title in /Applications/MAMP/htdocs/incipient.local/wp-content/plugins/super-cpt/includes/class-super-custom-post-meta.php on line 670

Notice: Undefined index: Team Member Title in /Applications/MAMP/htdocs/incipient.local/wp-content/plugins/super-cpt/includes/class-super-custom-post-meta.php on line 676

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/incipient.local/wp-content/plugins/super-cpt/includes/class-super-custom-post-meta.php:670) in /Applications/MAMP/htdocs/incipient.local/wp-admin/post.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/incipient.local/wp-content/plugins/super-cpt/includes/class-super-custom-post-meta.php:670) in /Applications/MAMP/htdocs/incipient.local/wp-includes/pluggable.php on line 875

Not sure if this is something I have done/got wrong but any help would be greatly appreciated!

Thanks in advance,
Paul

**Comment by mboynes** [comment]
That should be `'team_member_title'`
