### ISSUE TITLE
Super_Custom_Post_Meta->add_meta_box() can generate "undefined index" notices

### ISSUE THREAD

**Issue by GlassSteel** [mboynes/super-cpt#23]
Suggest adding a check via array_key_exists():
if ( !$this->is_assoc( $attr['fields'] ) ) {
            $new_fields = array();
            foreach ( $attr['fields'] as $field ) {
                if (array_key_exists('meta_key', $field)){
                    $new_fields[ $field['meta_key'] ] = $field;
                }
            }
            $attr['fields'] = $new_fields;
        }

**Comment by sunny04** [comment]
I have the same problem. Get Undefined index: default for almost every meta box.

**Comment by mattie02** [comment]
+1

**Comment by khawir** [comment]
Use 'default' => ' ' in the fields array of each meta box value and problem will go away :) e.g.
'fields' => array(
            'race_date' => array( 'type' => 'date', 'default' => '' ),
            'location' => array('type' => 'text', 'default' => ''),
            'laps' => array('type' => 'text', 'default' => '50'),
            'round' => array('type' => 'number', 'default' => '1'),
            'car_image' => array('type' => 'media', 'default' => ''),
            'event_image' => array('type' => 'media', 'default' => ''),
        )
