### ISSUE TITLE
Notice: Undefined index: when adding post

### ISSUE THREAD

**Issue by Nick-Lancaster** [mboynes/super-cpt#25]
Hi,

I'm receiving an error when I try to add a new post registered with SuperCPT. 

These errors only appear when the post is being added and don't seem to effect the data being stored. they disappear when editing the post.

Probably best illustrated by the attached images:
When posting
![screen shot 2013-09-21 at 11 16 54 am](https://f.cloud.github.com/assets/3607077/1184840/3ede0fb6-225c-11e3-8ea7-492406b38676.png)
When editing
![screen shot 2013-09-21 at 11 17 10 am](https://f.cloud.github.com/assets/3607077/1184839/3ee08b42-225c-11e3-8f8d-3a3ef3af2a81.png)

My code placed in functions.php is as follows:

```
function setup_custom_posts() {
    if ( ! class_exists( 'Super_Custom_Post_Type' ) )
        return;

    $workshops = new Super_Custom_Post_Type( 'workshop' );

    $workshops->add_meta_box( array(
        'id' => 'details',
        'fields' => array(
            'synopsis' => array( 'type' => 'textarea' ),
            'workshop-date' => array( 'type' => 'date' ),
            'venue' => array( 'type' => 'input' )
        )
    ) );

}
add_action( 'after_setup_theme', 'setup_custom_posts' );
```

I'm developing locally on a mac using MAMP, not sure if that makes any difference?

Any help much appreciated.

Thanks

**Comment by harmputman** [comment]
Exact same issue here. Also on line 298 in class-super-custom-post-meta.php. Never had this problem before!

**Comment by tnguyen14** [comment]
I'm having this problem as well

**Comment by tnguyen14** [comment]
One way to fix this issue for now is to add a blank default option when declaring the field

``` php
$cpt->add_meta_box(array(
    'fields' => array(
        'field' => array(
            'type' => 'text',
            'default' => ''
        )
    )
);
```

**Comment by mboynes** [comment]
See #23
