### ISSUE TITLE
WYSIWYG editors ... not support with wordpress sortcode

### ISSUE THREAD

**Issue by wson21** [mboynes/super-cpt#27]
WYSIWYG editors

not support with wordpress sortcode

please advices...thanks

**Comment by mboynes** [comment]
Shortcodes have nothing to do with the editor. Shortcodes are merely applied to the text of the main content editor when displaying that content through a filter on `'the_content'` which applies the function `do_shortcode()`. You can apply shortcodes to any additional blocks of text by applying the filter `'the_content'` to it, or calling the function `do_shortcode()` directly if you don't want all of the other goodness that comes with `'the_content'`.
