### ISSUE TITLE
How to remove CPT from search results?

### ISSUE THREAD

**Issue by ragzor** [mboynes/super-cpt#28]
Hello!

I wanted to remove my CPT from coming up in the search results Basically I want to add this:

'exclude_from_search' => true

Thanks alot!

**Comment by ragzor** [comment]
Umm

I achieved what I wanted to by wrapping the contents in the loop with this

```
<?php if (is_search() && ($post->post_type=='post')) : ?>

<?php endif; ?>
```

however I am not sure if it is the correct way of doing it :P

**Comment by mboynes** [comment]
Hi @ragzor, sorry for the delay here. I'm sure you've figured this out, but yes, `exclude_from_search` is what you want. There are [a few ways documented in the wiki](https://github.com/mboynes/super-cpt/wiki/Changing-Post-Type-and-Taxonomy-Parameters) to set the `register_post_type` arguments, e.g.

```
$my_cpt->exclude_from_search( true );
```
