### ISSUE TITLE
How can I add a field to the thumbnail metabox

### ISSUE THREAD

**Issue by Gyroscopic** [mboynes/super-cpt#33]
Hi there, 

I have a scpt with thumbnails enabled and want to add an additional field to the 'Featured Image' meta box, in this case a description.

I would like to use sixlives update of scpt to display a field_description but dont know how to access an existing metabox to apply the scpt code to.

Is this possible or is there maybe a wp hook (I cant find one) to add contents to an existing meta box?

Anyone have an idea?
Thanks in advance.

**Comment by mboynes** [comment]
Hey @Gyroscopic, sorry for the delay. You've probably figured this out by now, but you can modify that field with the `admin_post_thumbnail_html` filter, e.g.

``` php
function my_admin_post_thumbnail_html( $content ) {
    return $content . '<p>Insert description here</p>';
}
add_filter( 'admin_post_thumbnail_html', 'my_admin_post_thumbnail_html' );
```
