### ISSUE TITLE
Is there anyway to have conditional fields in the metaboxes, that only appear when another field gets chosen?

### ISSUE THREAD

**Issue by sunny04** [mboynes/super-cpt#36]
Hi,

I'm trying to figure out if I can have fields that only show if another field above them gets selected, through a check-box or a drop-down selection field.

Like for instance I want to give users the option to show or hide an element using a check-box. If they choose to show it, then I want to show them the options for that element, and if they choose to hide it then I wouldn't show them those options.

Any idea how to do it?

**Comment by sixlive** [comment]
I always use jQuery to show and hide. I add a js sheet to the admin head. http://codex.wordpress.org/Plugin_API/Action_Reference/admin_head

**Comment by sunny04** [comment]
@sixlive thanks for the tip, but I don't understand what '[for="wp_welcome_panel-hide"]' in the example on that page is. Can you please also explain that?

**Comment by sixlive** [comment]
I'm not sure what they are referring to there but here is a different example of how I use it.

``` php
function load_js_and_css() {
    wp_register_script('my-upload', get_template_directory() . '/admin.js', array('jquery'));
    wp_enqueue_script('my-upload');
}
add_action( 'admin_head', 'load_js_and_css' );
```

And my JS 

``` javascript
// If event all day is checked, hide start time meta field
jQuery('#scpt_meta_all-day-event').click(function(){
        if( jQuery(this).is(':checked') ) {
                jQuery('.start-time-wrap, .start-date-wrap, .start-time-am-pm-wrap').hide();
        } else {
                jQuery('.start-time-wrap, .start-date-wrap, .start-time-am-pm-wrap').show();
        }
});
```

Just a different example

**Comment by sunny04** [comment]
@sixlive Hi. Thank you for the example, I understand it now. However, I see that have you used 'admin_head', but I always thought you are supposed to use 'admin_enques_scripts' to add css or javascript in the admin pages, like so:

```
add_action( 'admin_enqueue_scripts', 'load_js_and_css' );
```

Instead of:

```
add_action( 'admin_head', 'load_js_and_css' );
```

Is there much of a difference between them?

**Comment by sixlive** [comment]
You know, I've never looked into that, you are correct. Use the action
admin_enqueue_scripts instead of admin_head... I will also start doing the
same.

**Comment by sunny04** [comment]
@sixlive You can also target specific pages with admin_enqueue_scripts and only load the files on those pages http://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts
Thanks for all the help.

Edit: Actually, loading of the files on different pages depends on the function and not the hook itself, you can probably do the same with admin_head too.

**Comment by sixlive** [comment]
Yup!
