### ISSUE TITLE
Set menu position with a decimal number

### ISSUE THREAD

**Issue by treiber** [mboynes/super-cpt#38]
Hey, I just realized that it is not possible to set the menu_position to a decimal number when creating a custom post type.
This could be useful for reordering the menu items though, since there's no easy way to display a cpt under the first separator but before the regular posts.

```
2 Dashboard
4 Separator
5 Posts
10 Media
15 Links
20 Pages
25 Comments
59 Separator
60 Appearance
65 Plugins
70 Users
75 Tools
80 Settings
99 Separator
```

Setting to cpt to 4 displays it below posts since this is the next available number. Working with decimal numbers (say 4.1) would display the correct order.

**Comment by mboynes** [comment]
Hey @treiber, you can actually do this if you set the position as a string. That is, instead of `4.1`, set it as `"4.1"`.
