### ISSUE TITLE
Is there a way to add a meta box to different post types?

### ISSUE THREAD

**Issue by sunny04** [mboynes/super-cpt#40]
Hello,

I'm loving SuperCPT so far, it really brings down the development time a great deal. But I was wondering if there was anyway we can add same meta boxes to different post types. As right now I have around 6 meta boxes that are the same in 'page', 'post' and 'portfolio' post types and it would be great if I can simply write the code for them ones and cast them to all these post types.

Thanks.

**Comment by mboynes** [comment]
No, there really isn't a way to do that. It would be a significant refactoring to make that possible.

If you're adding highly complex data structures, highly complex forms, repeating boxes across multiple post types, etc., you might consider using this plugin to build your post types and taxonomies, and another plugin [Fieldmanager](https://github.com/alleyinteractive/wordpress-fieldmanager) to drive your meta boxes.

Good luck!
