### ISSUE TITLE
Add metadata type of wysiwyg/textarea

### ISSUE THREAD

**Issue by AaronHolbrook** [mboynes/super-cpt#5]
For multiple editing areas/environments would be nice to have the wysiwyg editor

**Comment by mboynes** [comment]
Can you explain this a little more? I'm reading this as being able to having multiple wysiwyg editors, but it's possible to have unlimited wysiwyg editors using `'type' => 'wysiwyg'`

**Comment by AaronHolbrook** [comment]
Apologies, did not see that!
