### ISSUE TITLE
media select field type (enhancement request)

### ISSUE THREAD

**Issue by mosheeshel** [mboynes/super-cpt#7]
a field that includes a button that opens the media gallery, and when you select a file inserts the url into a text field.

like:
http://www.farinspace.com/wordpress-media-uploader-integration/
https://github.com/farinspace/wpalchemy/blob/dev/wp-content/wpalchemy/MediaAccess.php

In general that project (wpalchemy) has some nice ideas, but your execution, I think is much more elegant (for me as a developer at least)

**Comment by scottlee** [comment]
+1

**Comment by mboynes** [comment]
Duplicate of #4
