### ISSUE TITLE
Super CPT does not load assets correctly when being called from mu-plugins

### ISSUE THREAD

**Issue by AaronHolbrook** [mboynes/super-cpt#8]
On line 28: https://github.com/mboynes/super-cpt/blob/master/super-cpt.php#L28

Calling plugins_url does not report back the proper URL when Super-CPT is actually in the mu-plugins folder.

**Comment by AaronHolbrook** [comment]
Using the following define works correctly in mu-plugins:

`define( 'SCPT_PLUGIN_URL', plugins_url( '', __FILE__ ) . '/' );`

**Comment by mboynes** [comment]
This is resolved in master.

See 684434139df1f619c5f660f5139a20e3bb7c20f2.
