### ISSUE TITLE
Custom URL Re-writes

### ISSUE THREAD

**Issue by jasondavis** [mboynes/super-cpt#9]
When working with the Default custom post type API for WordPress it is possible to define custom re-write rules.   Is that possible here?  For example, right now all my custom post types are being prefixed with `blog/` and I do not want that to happen

**Comment by jasondavis** [comment]
I see it now is disabled in `class-super-custom-post-type.php` Would be nice if this was something that could be set in the API of this library

**Comment by mboynes** [comment]
Hi Jason, SuperCPT takes nothing away from the core functionality -- it only adds to it! You can alter the post type arguments (in your case, the "rewrite" parameter) in three ways:
1. In the construct, the fourth param is [register_post_type args](http://codex.wordpress.org/Function_Reference/register_post_type#Arguments)
2. By adding a filter hook for `scpt_plugin_default_cpt_options` (this would affect all post types you register with SuperCPT, so probably not the route you want to take)
3. By modifying the public property $cpt of the Super_Custom_Post_Type object you define. For instance,

`$movies = new Super_Custom_Post_Type( 'movie' );
$movies->cpt['rewrite'] = array( 'with_front' => false, 'slug' => 'movie' );`

See [register_post_type](http://codex.wordpress.org/Function_Reference/register_post_type#Arguments) for the details of what you need to set, but ultimately, it sounds like you want "with_front" set to false in the 'rewrite' param array.

**Comment by Mikesa1979** [comment]
Is there any reason why this would not change the menu position? 
I hope I understood the above example. 

<code>
function suppliers(){
    if(!class_exists('Super_Custom_Post_Type'))
        return;

```
$tsuppliers = new Super_Custom_Post_Type( 'trusted-supplier');
$tsuppliers->set_icon('user_add' );
$tsuppliers->cpt['rewrite']= array('show_in_menu' => true, 'menu_position' => 200);
```

 }
</code>

**Comment by Mikesa1979** [comment]
Was being really stupid :) 

This is the correct way to change the various default $args =>

<code>
 add_action('after_setup_theme','suppliers');
function suppliers(){
    if(!class_exists('Super_Custom_Post_Type'))
        return;

```
$tsuppliers = new Super_Custom_Post_Type( 'trusted-supplier');
$tsuppliers->set_icon('user_add' );
$tsuppliers->cpt['menu_position'] = 4 ;
```

 }
</code>
